### ISSUE TITLE
RUP throws an error when trying to use WordPress converter tool

### ISSUE THREAD

**Issue by githamm** [denverpost/rup#4]
I thought it might be VPN-related since I'm not on the network but then Tynin saw it in the office, too. She got it to work after a couple of tries, but when she sent me the html the converter spat out there weren't any styles in the content part of the newsletter, so I guess it didn't convert any of that.

I'll do some more extensive testing later.

![rup-error](https://user-images.githubusercontent.com/6498109/45513499-6ee84e00-b768-11e8-8622-1eacf992eccf.png)

**Comment by freejoe76** [comment]
So `FTP_SERVER` is a constant, but it has to be defined somewhere, and there's nothing in the code repo that defines it. It could be getting defined on the server itself, I'm going to log into the server and see about that.

**Comment by freejoe76** [comment]
Okay so the file that was loading the constants wasn't being loaded. It is now, as of commit d49f744.
